# Labeler configuration for mcpambassador/server
# Format: actions/labeler@v5 (changed-files with glob patterns)

"area: core":
  - changed-files:
      - any-glob-to-any-file: "packages/core/**"

"area: auth":
  - changed-files:
      - any-glob-to-any-file:
          - "packages/authn-*/**"
          - "packages/authz-*/**"

"area: server":
  - changed-files:
      - any-glob-to-any-file: "packages/server/**"

"area: contracts":
  - changed-files:
      - any-glob-to-any-file: "packages/contracts/**"

"area: spa":
  - changed-files:
      - any-glob-to-any-file: "packages/spa/**"

"area: audit":
  - changed-files:
      - any-glob-to-any-file: "packages/audit-*/**"

"area: protocol":
  - changed-files:
      - any-glob-to-any-file: "packages/protocol/**"

"area: database":
  - changed-files:
      - any-glob-to-any-file:
          - "packages/core/src/schema.ts"
          - "packages/core/drizzle/**"

"area: docker":
  - changed-files:
      - any-glob-to-any-file:
          - "Dockerfile"
          - "docker-compose.yml"

"area: ci":
  - changed-files:
      - any-glob-to-any-file: ".github/**"

"area: dependencies":
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "pnpm-lock.yaml"
          - "**/package.json"

"area: docs":
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - "**/*.md"
