name: Bug Report
description: Report a bug in MCP Ambassador Server
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in as much detail as possible.

        **Security vulnerability?** Please use [private vulnerability reporting](../../security/advisories/new) instead.

  - type: input
    id: version
    attributes:
      label: Server Version
      description: "Run: `docker inspect mcpambassador-server --format '{{.Config.Labels.version}}'` or check your deployment"
      placeholder: "e.g. 0.8.0-beta.1"
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      options:
        - Docker Compose (self-hosted)
        - Docker standalone
        - Kubernetes
        - Development (pnpm dev)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Configure MCP with...
        2. Connect client with...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: "Paste sanitized server logs (remove credentials/tokens). Use JSON log format if available."
      render: text

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS: Ubuntu 24.04
        - Node.js: 20.11.0
        - Docker: 25.0.2
        - Client version: 0.8.0-beta.1
